export const users = [
  {
    id: "testLoginUserId59234619",
    name: "テスト太郎",
    email: "test@example.com",
    comment: "",
    division: "人事部",
    extension: "999",
  },
  {
    name: "小林 穣二",
    email: "jouji_kobayashi@example.com",
    comment: "",
    division: "広報部",
    extension: "8101",
  },
  {
    name: "鳥井 幸仁",
    email: "yukihito_torii@example.com",
    comment: "",
    division: "制作部",
    extension: "8102",
  },
  {
    name: "藤沢 周平",
    email: "shuhei_fujisawa@example.com",
    comment: "",
    division: "広報部",
    extension: "8103",
  },
  {
    name: "杉本 一郎",
    email: "ichiro_sugimoto@example.com",
    comment: "",
    division: "広報部",
    extension: "8104",
  },
  {
    name: "松永 重明",
    email: "shigeaki_matatsuna@example.com",
    comment: "",
    division: "営業部",
    extension: "8105",
  },
  {
    name: "阿江 泰治",
    email: "yasuji_ae@example.com",
    comment: "",
    division: "制作部",
    extension: "8106",
  },
  {
    name: "杉山 高義",
    email: "takayoshi_sugiyama@example.com",
    comment: "",
    division: "デジタル部",
    extension: "8107",
  },
  {
    name: "榎本 道臣",
    email: "michiomi_enomoto@example.com",
    comment: "",
    division: "人事部",
    extension: "8108",
  },
  {
    name: "美原 良材",
    email: "yoshiki_mihara@example.com",
    comment: "",
    division: "広報部",
    extension: "8109",
  },
  {
    name: "白桃 邦彦",
    email: "kunihiko_shirato@example.com",
    comment: "",
    division: "営業部",
    extension: "8110",
  },
  {
    name: "加藤 光宏",
    email: "mitsuhiro_kato@example.com",
    comment: "",
    division: "制作部",
    extension: "8111",
  },
  {
    name: "西山 彩加",
    email: "ayaka_nishiyama@example.com",
    comment: "",
    division: "デジタル部",
    extension: "8112",
  },
  {
    name: "巽 次男",
    email: "tsugio_tatsumi@example.com",
    comment: "",
    division: "広報部",
    extension: "8113",
  },
  {
    name: "宮崎 剛",
    email: "tsuyoshi_miyazaki@example.com",
    comment: "",
    division: "広報部",
    extension: "8114",
  },
  {
    name: "堀江 克典",
    email: "katsunori_horie@example.com",
    comment: "",
    division: "制作部",
    extension: "8115",
  },
  {
    name: "辻 拓也",
    email: "takuya_azalea@example.com",
    comment: "",
    division: "広報部",
    extension: "8116",
  },
  {
    name: "小滝 ひかる",
    email: "hikaru_kotaki@example.com",
    comment: "",
    division: "人事部",
    extension: "8117",
  },
  {
    name: "芦田 望",
    email: "nozomi_ashida@example.com",
    comment: "",
    division: "営業部",
    extension: "8118",
  },
  {
    name: "加藤 舞子",
    email: "maiko_kato@example.com",
    comment: "",
    division: "制作部",
    extension: "8119",
  },
  {
    name: "福倉 耕一",
    email: "koichi_fukukura@example.com",
    comment: "",
    division: "制作部",
    extension: "8120",
  },
  {
    name: "寺田 愛理",
    email: "airi_terada@example.com",
    comment: "",
    division: "営業部",
    extension: "8121",
  },
  {
    name: "佐々木 洋",
    email: "hiroshi_sasaki@example.com",
    comment: "",
    division: "デジタル部",
    extension: "8122",
  },
  {
    name: "磯村 要",
    email: "kaname_isomura@example.com",
    comment: "",
    division: "制作部",
    extension: "8123",
  },
  {
    name: "中嶋 彩",
    email: "aya_nakashima@example.com",
    comment: "",
    division: "人事部",
    extension: "8124",
  },
  {
    name: "城定 省二",
    email: "shoji_jojo@example.com",
    comment: "",
    division: "広報部",
    extension: "8125",
  },
  {
    name: "秋山 義秋",
    email: "yoshiaki_akiyama@example.com",
    comment: "",
    division: "制作部",
    extension: "8126",
  },
  {
    name: "岡本 治",
    email: "osamu_okamoto@example.com",
    comment: "",
    division: "営業部",
    extension: "8127",
  },
  {
    name: "柴田 雄介",
    email: "yusuke_shibata@example.com",
    comment: "",
    division: "営業部",
    extension: "8128",
  },
  {
    name: "一之瀬 夢吾",
    email: "yugo_ichinose@example.com",
    comment: "",
    division: "制作部",
    extension: "8129",
  },
  {
    name: "増本 博土",
    email: "hiroto_masumoto@example.com",
    comment: "",
    division: "人事部",
    extension: "8130",
  },
  {
    name: "上原 美希",
    email: "miki_uehara@example.com",
    comment: "",
    division: "人事部",
    extension: "8131",
  },
  {
    name: "越田 亜弥華",
    email: "ayaka_koshida@example.com",
    comment: "",
    division: "営業部",
    extension: "8132",
  },
];
